services:
  nats-server:
    image: nats:2.10.0-alpine
    ports:
      - "4222:4222"
  db-competitions:
    container_name: competitions_database
    image: mysql:8.4.1
    restart: always
    volumes:
      - competitions-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=competitions_db

volumes:
  competitions-mysql-data: