services:
  nats-server:
    image: nats:2.10.0-alpine
    ports:
      - "4222:4222"
  db-stats:
    container_name: stats_database
    image: mysql:8.4.1
    restart: always
    volumes:
      - stats-mysql-data:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=stats_db

volumes:
  stats-mysql-data: